import { Button, HorizontalBox, VerticalBox, AboutSlint } from "std-widgets.slint";

export struct Test {
    T1: string,
    T2: int,
    T3: bool,
}

export component AppWindow inherits Window {
    height: 480px;
    width: 640px;
    background: #2362c2;

    in-out property<int> counter: 42;
    in-out property<string> text1: "";
    in-out property <bool> bool1: true;
    in-out property <image> img;
    in-out property <Test> testStruct;
    callback request-increase-value();

    // binding
    in-out property<length> Width <=> root.width;

    VerticalBox {
        Text {
            horizontal-alignment: center;
            text: "Counter: \{root.counter}";
        }
        Image {
            source: img;
        }
        Text {
            horizontal-alignment: center;
            text: "\{root.text1}";
        }
        Text {
            horizontal-alignment: center;
            text: "\{root.testStruct.T1}";
        }
        HorizontalBox {
            alignment: center;
            Button {
                text: "Increase value";
                clicked => {
                    root.text1 = "From Slint";
                    testStruct.T1 = "CLICKED";
                    testStruct.T2 = 42;
                    testStruct.T3 = true;
                    root.request-increase-value();
                }
            }
        }
    }
}
